# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # gradle(task: "clean bundleRelease")
    # gradle(
    #   task: "assemble",
    #   build_type: "Release"
    # )
    upload_to_play_store(
      json_key: "./fastlane/playstore_key.json",
      track: "internal",
      # release_status: "draft",
      # skip_upload_changelogs: true,
      aab: "../build/app/outputs/bundle/prodRelease/app-prod-release.aab"
    )
  end

  desc "Increase version code"
  lane :increment_build_num do
    previous_build_number = google_play_track_version_codes(
      package_name: 'hcmus.lettutor.tutor_flutter_app',
      track: "internal",
      json_key: "./fastlane/playstore_key.json",
    )[0]

    current_build_number = previous_build_number + 1

    increment_version_code(
      gradle_file_path: "./app/build.gradle",
      version_code: current_build_number
    )
 end
end
