name: CD
on:
  push:
    branches: ["chores/test_cd"]

jobs:
  deploy_ios:
    name: deploy iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: "develop"
    - run: |
          ls ${{ github.workspace }}
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        cache: true
    - run: |
          flutter --version
          flutter pub get
    - name: run fastlane
      working-directory: ./ios
      run: |
          pod install
          fastlane release

  build_and_deploy_android:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: "develop"
    - run: |
          ls ${{ github.workspace }}
    - uses: subosito/flutter-action@v2
      with:
        channel: "stable"
        cache: true
    - run: flutter pub get
    - name: Run fastlane
      working-directory: ./android
      run: fastlane deploy